/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Leonardo
 */
public class TelaQuestaoProfessor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaQuestaoProfessor.class.getName());

    /**
     * Creates new form TelaQuestaoProfessor
     */
    public TelaQuestaoProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPrincipal = new javax.swing.JPanel();
        jpnlTopo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblQuestaoAtual = new javax.swing.JLabel();
        jlblNivel = new javax.swing.JLabel();
        lblPontos = new javax.swing.JLabel();
        jAlternativaA = new javax.swing.JButton();
        jAlternativaB = new javax.swing.JButton();
        jAlternativaC = new javax.swing.JButton();
        jAlternativaD = new javax.swing.JButton();
        jpnlEnunciado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnProximaQuestao1 = new javax.swing.JButton();
        jDicaTela = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jpnlTopo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO CPS.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo etec.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO LAB QUIZ.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        lblQuestaoAtual.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblQuestaoAtual.setText("Questão X de Y");

        jlblNivel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jlblNivel.setText("Nível: Fácil");

        lblPontos.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblPontos.setText("Pontos: 0");

        javax.swing.GroupLayout jpnlTopoLayout = new javax.swing.GroupLayout(jpnlTopo);
        jpnlTopo.setLayout(jpnlTopoLayout);
        jpnlTopoLayout.setHorizontalGroup(
            jpnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlTopoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(lblQuestaoAtual)
                .addGap(56, 56, 56)
                .addComponent(jlblNivel)
                .addGap(46, 46, 46)
                .addComponent(lblPontos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlTopoLayout.setVerticalGroup(
            jpnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(lblQuestaoAtual)
                    .addComponent(jlblNivel)
                    .addComponent(lblPontos))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jAlternativaA.setBackground(new java.awt.Color(39, 51, 54));
        jAlternativaA.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jAlternativaA.setForeground(new java.awt.Color(255, 255, 255));
        jAlternativaA.setText("Alternativa A");
        jAlternativaA.setAutoscrolls(true);
        jAlternativaA.addActionListener(this::jAlternativaAActionPerformed);

        jAlternativaB.setBackground(new java.awt.Color(39, 51, 54));
        jAlternativaB.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jAlternativaB.setForeground(new java.awt.Color(255, 255, 255));
        jAlternativaB.setText("Alternativa B");

        jAlternativaC.setBackground(new java.awt.Color(39, 51, 54));
        jAlternativaC.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jAlternativaC.setForeground(new java.awt.Color(255, 255, 255));
        jAlternativaC.setText("Alternativa C");

        jAlternativaD.setBackground(new java.awt.Color(39, 51, 54));
        jAlternativaD.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jAlternativaD.setForeground(new java.awt.Color(255, 255, 255));
        jAlternativaD.setText("Alternativa D");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("ENUNCIADO:");

        jLabel3.setText("imagem questao");

        javax.swing.GroupLayout jpnlEnunciadoLayout = new javax.swing.GroupLayout(jpnlEnunciado);
        jpnlEnunciado.setLayout(jpnlEnunciadoLayout);
        jpnlEnunciadoLayout.setHorizontalGroup(
            jpnlEnunciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlEnunciadoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlEnunciadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(73, 73, 73))
        );
        jpnlEnunciadoLayout.setVerticalGroup(
            jpnlEnunciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlEnunciadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        btnProximaQuestao1.setBackground(new java.awt.Color(153, 0, 0));
        btnProximaQuestao1.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        btnProximaQuestao1.setForeground(new java.awt.Color(255, 255, 255));
        btnProximaQuestao1.setText("Próxima questão");
        btnProximaQuestao1.setToolTipText("");
        btnProximaQuestao1.addActionListener(this::btnProximaQuestao1ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Ajuda disponível:");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("DICAS");

        javax.swing.GroupLayout jDicaTelaLayout = new javax.swing.GroupLayout(jDicaTela);
        jDicaTela.setLayout(jDicaTelaLayout);
        jDicaTelaLayout.setHorizontalGroup(
            jDicaTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDicaTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDicaTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jDicaTelaLayout.setVerticalGroup(
            jDicaTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDicaTelaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnlPrincipalLayout = new javax.swing.GroupLayout(jpnlPrincipal);
        jpnlPrincipal.setLayout(jpnlPrincipalLayout);
        jpnlPrincipalLayout.setHorizontalGroup(
            jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnProximaQuestao1))
                    .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpnlEnunciado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                                .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jAlternativaB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jAlternativaA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jAlternativaC, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jAlternativaD, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDicaTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlPrincipalLayout.createSequentialGroup()
                .addComponent(jpnlTopo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnlPrincipalLayout.setVerticalGroup(
            jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                .addComponent(jpnlTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                        .addComponent(jpnlEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAlternativaC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAlternativaA, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAlternativaB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAlternativaD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnProximaQuestao1))
                    .addComponent(jDicaTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jpnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jpnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAlternativaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlternativaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAlternativaAActionPerformed

    private void btnProximaQuestao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximaQuestao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProximaQuestao1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaQuestaoProfessor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProximaQuestao1;
    private javax.swing.JButton jAlternativaA;
    private javax.swing.JButton jAlternativaB;
    private javax.swing.JButton jAlternativaC;
    private javax.swing.JButton jAlternativaD;
    private javax.swing.JPanel jDicaTela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jlblNivel;
    private javax.swing.JPanel jpnlEnunciado;
    private javax.swing.JPanel jpnlPrincipal;
    private javax.swing.JPanel jpnlTopo;
    private javax.swing.JLabel lblPontos;
    private javax.swing.JLabel lblQuestaoAtual;
    // End of variables declaration//GEN-END:variables
}
